meta_data:
  script_path: run_scripts/adp_bc_script.py
  exp_name: adp_bc_hopper_4_hyper_search
  description: Train an adversarial IRL model
  num_workers: 1 # 64
  num_gpu_per_worker: 1 # 0
  num_cpu_per_worker: 32 # 2
  mem_per_worker: 4gb
  partitions: cpu
  node_exclusions: gpu048,gpu024,gpu025,gpu012,gpu027
# -----------------------------------------------------------------------------
variables:
  seed: [723894]

# -----------------------------------------------------------------------------
constants:
  expert_name: 'norm_hopper_4_demos_sub_20'
  expert_idx: 0
  scale_env_with_demo_stats: false
  minmax_env_with_demo_stats: true

  critic_num_blocks: 2
  critic_hid_dim: 128
  critic_hid_act: tanh
  critic_use_bn: false

  policy_net_size: 256
  policy_num_hidden_layers: 2

  adp_bc_params:
    mode: 'MLE'

    num_epochs: 202
    num_steps_per_epoch: 100000
    num_steps_between_train_calls: 1000
    max_path_length: 1000
    min_steps_before_training: 5000

    eval_deterministic: true
    num_steps_per_eval: 20000
    
    replay_buffer_size: 20000
    no_terminal: false
    wrap_absorbing: false

    num_update_loops_per_train_call: 1
    num_adp_updates_per_loop_iter: 1
    num_bc_updates_per_loop_iter: 1

    critic_lr: 0.0003
    critic_momentum: 0.0
    # use_grad_pen: true
    critic_optim_batch_size: 256
    n_itr_critic: 5

    grad_pen_weight: 10.0

    lr: 0.0003
    momentum: 0.9
    batch_size: 256

    save_best: true
    freq_saving: 20
    save_replay_buffer: false
    save_environment: false
    save_algorithm: false

  env_specs:
    env_name: 'hopper'
    env_kwargs: {}
    eval_env_seed: 78236
    training_env_seed: 24495
